- hosts: all
  vars: 
    packages:
       - tree
       - apache
       - wget
       - git
       - unzip
  become: yes
  tasks:
  - name: Install apache 
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present